name = "ROMEO"
uuid = "1ea8258b-a15d-4adb-ad20-01632f467a84"
authors = ["Korbinian Eckstein", "Barbara Dymerska"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"

[targets]
test = ["Test", "NIfTI"]
